### ISSUE TITLE
CentOS/RHEL Compatibility

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#126]
I don't expect this will be a focus of work from the infochimps side, but if anyone would like to push in patches -- or reply on this issue with a "here's what I had to do to get these cookbooks working on CentOS or other non-ubuntu distribution" we're all ears.

@jessehu - I see that you have made ironfan work with vSphere provisioner and with CentOS. What were the major hurdles?

**Comment by jessehu** [comment]
@mrflip To make Ironfan work with vSphere and CentOS, I have made the following changes:

1) change the code in cookbooks that hardcoded for ubuntu to work on CentOS (including: install hadoop package yum repository instead of apt repository, etc). We move to CentOS because CDH4B1 only provide rpm packages.
2) add class vSphere in cloud.rb and code in discovery.rb for providing vSphere specific configuration
3) bypass the code that only works for EC2 (such as getting addresses, volumes from EC2 doesn't work for Fog::vSphere)
4) enhanced Fog::vSphere

Regarding 2) and 3),  I think it would be better to do some refactoring in cloud.rb/discovery.rb to provide a more generic IaaSCloud layer, so we don't need to add 'case cluster.cloud.name' everywhere to adapter to more clouds.  The design of code structure would be similar to Fog (since Ironfan uses Fog).

If you get some time , could we have a discussion on the refactoring?  Thanks :)

**Comment by temujin9** [comment]
We've actually done a fair amount of this work now, for a client. I'm closing this as finished; open new tickets if specific components are failing under CentOS or RHEL.
