### ISSUE TITLE
no_security_group attr no longer available (was attrs not passed down to facet during construction)

### ISSUE THREAD

**Issue by agentgonzo** [infochimps-labs/ironfan#140]
When trying to create a facet without automatically creating a security group, the attrs object isn't passed down to the facet constructor from the cluster constructor.

Eg, in my cluster file, the following does NOT work:
  facet :myfacet, {:no_security_group => true} do
    instances           1
  end

Here is the fix:
diff --git a/gems/1.9.1/gems/ironfan-3.1.5/lib/ironfan/cluster.rb b/gems/1.9.1/gems/ironfan-3.1.5/lib/ironfan/cluster.rb
index 7ceea2e..7eba600 100644
--- a/gems/1.9.1/gems/ironfan-3.1.5/lib/ironfan/cluster.rb
+++ b/gems/1.9.1/gems/ironfan-3.1.5/lib/ironfan/cluster.rb
@@ -50,7 +50,7 @@ module Ironfan
     #
     def facet(facet_name, attrs={}, &block)
       facet_name = facet_name.to_sym
-      @facets[facet_name] ||= Ironfan::Facet.new(self, facet_name)
-      @facets[facet_name] ||= Ironfan::Facet.new(self, facet_name, attrs)
     @facets[facet_name].configure(attrs, &block)
     @facets[facet_name]
   end

**Comment by temujin9** [comment]
Thanks. Added that fix to v3.x.

I think the attribute resolution problem has been done correctly in the current version of Ironfan. However, I don't find the no_security_group flag in [the new ensure_groups code](https://github.com/infochimps-labs/ironfan/blob/master/lib/ironfan/provider/ec2/security_group.rb#L85). I'm updating this issue, since I intended to follow the v3 DSL as closely as possible, and this was an oversight.

I'm curious, however: what's the use-case for skipping the implied facet security group? I've found it easy enough to ignore the ones that don't actually matter, especially since the AWS console gives you per-instance visibility into what ports are opened by what group.

**Comment by agentgonzo** [comment]
The use-case is that we've currently got over 400 security groups and many of them are not used or needed. It's not a major thing and we can ignore them, but when we only use about 15 of them all that other clutter gets in the way - especially when we keep on creating test clusters under different names :-(

Thanks for the fixk.
