### ISSUE TITLE
knife cluster launch --bootstrap should respect environment

### ISSUE THREAD

**Issue by lastobelus** [infochimps-labs/ironfan#148]
When I run 

```
knife cluster launch SOME_CLUSTER-SOME_FACET --bootstrap
```

the node environment gets set correctly on the chef_server at launch, however, the first chef run sets it back to _default.

It does work if you pass the --environment option:

```
knife cluster launch SOME_CLUSTER-SOME_FACET --bootstrap --environment dev
```

I think knife cluster launch bootstrap should respect the cluster or facet environment setting.

**Comment by nickmarden** [comment]
+1 for this - we have workarounds in our cluster.rb files for exactly this issue.

**Comment by mrflip** [comment]
@nickmarden can you paste in the code you use to work around? I can turn it into a proper patch.

**Comment by nickmarden** [comment]
```
Ironfan.cluster 'integration' do
  ...
  # TODO: For some reason this isn't set automatically. Can't imagine why.
  Chef::Config[:environment] = 'integration'
end
```

**Comment by nickmarden** [comment]
To be more complete, I should have said this:

```
Ironfan.cluster 'integration' do
  environment :integration
  ...
  # TODO: For some reason this isn't set automatically. Can't imagine why.
  Chef::Config[:environment] = 'integration'
end
```

**Comment by mrflip** [comment]
Ah -- so the request is that the environment declared in the cluster file is also crammed into the Chef::Config? That's straightforward.

**Comment by mrflip** [comment]
Or maybe not. The environment is in principle set on any of cluster, facet or server. The Chef::Config variable is I believe shared among threads.

Lemme see where in the chef code that value goes. If it is governed by Chef::Config, our choices:
- a) environment is only a cluster attribute. Since commands are currently scoped by cluster, a constant value is fine. 
- b) we get dirty.

**Comment by mrflip** [comment]
actually I can add 
- c) throw an error if there is an inconsistent set of environment specs across the slice. If your facets have different environments, it makes sense to ask you to manage them independently.

**Comment by nickmarden** [comment]
To be clear, in (c) you're suggesting that you would allow the environment to also be a per-facet or per-server attribute, but you'd barf if there was inconsistency. This would enforce the behavior that would exist if you simply removed the per-facet or per-server attribute altogether, but in a way that is backwards compatible with existing cluster-files. Sort of.

Am I getting it right? If so, I'd say that you should just go with (a) and note in your Upgrading-to-v4 notes that such pathology is no longer tolerated. But that's just one guy's HO.

**Comment by temujin9** [comment]
I'm going to veto (a) and (c): we use different environments in facets, I have several examples of why we would want to continue, and I don't want to change the interface more than I already have. I'll look into code further, but it **shouldn't** require getting terribly dirty to fix this: I suspect that config variable feeds into something more modular.

**Comment by mrflip** [comment]
I did a little dip into the bootstrap code; in order to make bootstrap work if there are multiple environments in the slice, you'll have to identify the subgroups with each environment and coordinate launching an ssh session on each. `Knife::Bootstrap` prepares a single template file that draws on the `Chef::Config[:environment]` setting, and uses that as the command to a knife::Ssh session. At that point it's in Net::Ssh's hands. Anything we did that was non-uniform would lose parallel ssh sessions.

So I implemented (c). Knife checks the slice and, as long as all the machines you're bootstrapping live in the same environment, sets the Chef::Config and carries on. If you have multiple environments it explains and raises an exception.

You can still have a cluster with multiple environments, and do anything you like. When it comes time to bootstrap them, you have to do so in groups by environment. Unless you can figure out something I couldn't seems like a workable limitation.
