### ISSUE TITLE
Need effective mechanisms for support, processing minor contributions/issues

### ISSUE THREAD

**Issue by nickmarden** [infochimps-labs/ironfan#152]
At Get Satisfaction, we are very enthusiastic users of ironfan. It's brilliant!

Our use of ironfan-homebase is predicated on the idea that it is still somewhat sharp around some edges, but that such sharpness is OK because we'll be regularly pulling in changes as they occur in ironfan-homebase's master. Specifically, our repo of ironfan-homebase is a branch from infochimps/ironfan-homebase, and we regularly rebase our changes to sit on top of whatever the current master version of infochimps/ironfan-homebase might be. Combined with some continuous integration that we've built around our own clusters, we are able to keep a high degree of confidence that our ironfan-homebase will continue to work even as we absorb changes from the upstream infochimps master branch.

However...there are times when we encounter true show-stopper problems such as https://github.com/infochimps-labs/ironfan/pull/151 and we can't proceed until they are fixed. In this case, we wind up with commits in our ironfan-homebase branch that are modifications to what we would consider the 'core' of ironfan-homebase and therefore prone to cause rebase complexity over time.

Also, there are times when we think we find behaviors which are different than what is documented in the various Ironfan support resources (wiki, code examples, etc.), and we often feel as though we are on our own when we encounter these issues.

So, as we move towards using ironfan for our entire system, we're getting a little nervous about three things:
- There does not yet seem to be a community in which Ironfan users can help each other out, which is a shame as there appear to be many people using Ironfan
- The rate at which pull requests are absorbed seems slow, especially in cases of extremely simple pull requests
- There have not been (or we have not seen) clear expectations set around the maintenance lifetimes of minor versions (e.g., 3.1 vs. 3.2) of the ironfan code

We'd like to know what we, as members of the ironfan user community, can do to help address the first two issues, and what guidance Infochimps can give us on the third.

**Comment by temujin9** [comment]
There are a couple of forces at work here:
- I'm the only employee dedicated to working on the core of ironfan at the moment, and I've also got responsibility for keeping all our project servers copacetic. My head is very full, so some things happen slower than I'd like.
- I've been burning the midnight oil to make Ironfan multicloud capable, which has been occupying most of my ironfan headspace.

Regarding your worries:
- I would love to get a community organized (preferably on an email list of some sort), but I'm just not sure I can devote the necessary cycles to moderating. Someone who was able to do the job justice would have a large voice in what it asks of us (hint, hint).
- Pull requests have been clumping up because I wanted to accept them correctly, so that they make it into the multicloud code. In general, if a pull request isn't in yet, there's usually a good (if not always unstated) reason; if you're concerned about a particular one, feel free to comment on the request itself to ask what the situation is.
- I'm not sure what exactly to do with respect to maintenance expectations. Maintaining two major branches (3.X and 4.X [aka multcloud]) is probably going to be enough headache that I expect to be announcing a sunset date for 3.X soon after I announce 4.X is in beta. I expect minor versions branches aren't going to get much love, beyond a recommendation to track the major version instead. I'll listen to counter-arguments on that, though.

Can you offer help on the community organization, or recommend someone who could? I'd be glad to work with my bosses to get them the necessary support to do so. My main criterion is that they be an active ironfan user, so that the lingo doesn't interfere with their duties.

**Comment by nickmarden** [comment]
Sorry I took so long to get back to you (irony sandwich!) but this sparked some internal discussion here at Get Satisfaction that we needed to get through before we could come back with a specific proposal.

Get Satisfaction would love to be part of, and to help lead, a community organization for Ironfan. Since our primary interest is to make sure that Ironfan has sufficient traction to remain viable and robust over the long term, we would propose starting with a moderated mailing list that would have as its moderators you, myself, Michael Mittelstadt (@meekmichael), and any other "power users" of Ironfan who might be interested. (People, chime in here!)

The purpose of this mailing list would be:
- To help Ironfan users get the support they need with questions about using Ironfan
- To provide a clearer picture into the size of the Ironfan community and the ways in which Ironfan is being used
- To provide an environment for discussing perceived bugs or inadequacies in Ironfan, and how they can be fixed or worked around
- To provide an environment for vetting proposed changes to Ironfan

Secondarily, we think that it may make sense to create one or more moderated community repos that would allow for submission and discussion of changes outside of the "official" Infochimps ironfan/ironfan-pantry repos. The goal of these community repos would not be to fork development of Ironfan, but to provide a place where bug fixes and changes could be tested and turned around quickly without putting pressure on Infochimps to maintain a very fast response rate to new issues and requests. Furthermore, it would provide a place where the community could devise and implement strategies on CI, support, and version life cycles...preferably strategies that don't involve @temujin9 giving up sleep permanently. 

In turn, Infochimps would be asked to consider this repo to be a "preferred provider" of pull requests and to maintain a fairly close relationship with its maintainers in order to minimize divergence between the community and official repositories. 

Please let us know what you think about these ideas.

**Comment by temujin9** [comment]
Nick, thank you for the offer. I've been heavily stacked this week, and I'd
like to make sure my bosses are on-board (and look closer myself) before we
accept, but I'm very happy with the basic idea. Hold tight for just a
little longer . . .

Cheers,

## 

Nathaniel Eliot
Ops Engineer
InfoChimps.com

**Comment by nickmarden** [comment]
OK, also worth noting: I'm going to be in Austin from October 8-10, visiting the Get Satisfaction offices there. If there is any value in meeting face-to-face to discuss this, it would be convenient to do so then.

**Comment by mrflip** [comment]
Really psyched about this BTW. Thanks Nick, and we'd love to meet you & the gang for a beer.

I'd like to actively recruit and encourage cookbook maintainers -- submit a thoughtful-enough pull request and we will punish you with commit access to the repo and encouragement to review future PRs. (Of course we'll make it seem like that's a desirable thing to have.) I've had that trick played on me to great effect in the past. 

I have way more battle scars from being speared by a fork than knocked off balance by a push. A bug fix like the one you highlighted shouldn't need more than someone's '+1' to go in -- community members should be encouraged to do so.

I think ironfan-pantry can serve as that community repo for the existing cookbooks, with a contrib-pantry for ironfantastic cookbooks that we don't run in production. We'll obviously have some strong opinions about things that we are downstream from, but I'm ready to find out where those strong opinions differ from consensus and adapt accordingly.

proposed:
- Maintainers are asked to push changes via pull requests, @temujin9 excluded
- White-elephant commit bit
- Make a list of cookbooks, assign them a grade on how Ironfan-tastic they are (from ganglia=A to mongo=F), and encourage folks to take lieutenantship over them.

re: Continuous Integration, temujin9 and @dieterichlawson have cooked up something pretty awesome that we're spooling up internally -- machine-level integration tests based on the announcement (ie. if a component announces a capability on port 8080, the integration tests check that it is open, gives a correct heartbeat response, etc). You guys should chat about that too.

**Comment by temujin9** [comment]
Having a tangible community to talk to about Ironfan will be **very** helpful, even aside from potential code contributions. Thank you again for taking this on.

I'm going to hold off on changing commit rights, and ask that we table the community repos idea, for the moment. Let's see if community engagement, quicker response on pull requests, and the forthcoming CI can get the code flowing cleanly. Community should have a chance to weigh in on deeper solutions, if it turns out we do need them.

I'll be doing a talk on Ironfan, 7pm on the 8th, at [the Copperegg offices](https://plus.google.com/106593429576106129861/about?gl=us&hl=en). If you're interested in taking part, it could certainly help to drum up participation. Either way, we should certainly meet, at [our offices](https://plus.google.com/118088957256825268330/about?gl=us&hl=en) or yours.

**Comment by rberger** [comment]
I'm interested in this as well. We're feeling the same was as Nick and GetSatisfaction folks. We're pretty committed now to Ironfan at this time. But its worrisome that a true community effort hasn't emerged. Emergence of such communities is the number one indicator of future success or failure for similar projects in my experience.

By the way, any of you all going to be at the Chef Community Conference in October. That could be a good place to sync and possibly launch something publicly. I'll be there.

**Comment by nickmarden** [comment]
@rberger - Are you talking about the one in Seattle, or somewhere else?

**Comment by nickmarden** [comment]
@temujin9 and @mrflip - yes to both the Copperegg talk and your offer for beer - my email address is in my github profile.

**Comment by rberger** [comment]
@nickmarden The one in Seattle in late October

**Comment by temujin9** [comment]
@nickmarden We've finally gotten Google Groups set up as we needed to. There's still SNAFU with email and the mailing list, but the [web interface](https://groups.google.com/a/infochimps.com/d/forum/ironfan-users) should be working. You're set up as admin, so feel free to poke around at the settings and start inviting folks you know are interested.

@rberger Unfortunately, we're not going to the Community Conference. If you could talk up the mailing list (and the latest version of Ironfan) there, I'd be grateful.

**Comment by rberger** [comment]
Ok, signed up for the google groups. Shall I tweet its link?

---

Robert J Berger  - Runa Inc
Co-Founder / CTO / CloudMaster
2 West 5th Ave Suite 300
San Mateo, CA 94402
+1 408-838-8896

**Comment by temujin9** [comment]
Hold off for a day or two, to see if we can't get the underlying mail issue cleaned up; I'd rather not start it all off with something that breaks user assumptions. But if you're getting to the end of the conference, or people are clamoring for the address before that, go ahead.

**Comment by nickmarden** [comment]
Thanks @temujin9 - this looks like a good structure for the mailing list. When you have the email issues (whatever they might be) sorted out, feel free to go ahead and broadcast the web address in the ironfan and ironfan-homebase repos. Operators are ready and standing by!

![One type of operator](http://www.gulker.com/blog/wp-content/2007/09/tank1.jpg)

**Comment by temujin9** [comment]
It looks like we're on track for a migration tomorrow night, so _:cross fingers:_ everything should be ready to go Friday. I'll let you know here when we're sure.

**Comment by temujin9** [comment]
We're all migrated over, and we should be all set to go with the list. We've got a blog post describing the new codebase and the mailing list dropping in a little over an hour. Closing this, but definitely let us know if you need help with any part of the list management.
