### ISSUE TITLE
c1.medium instances broken

### ISSUE THREAD

**Issue by fractaloop** [infochimps-labs/ironfan#182]
When attempting to `knife cluster launch broken` it dies out with a nil error.

The broken cluster def is as follows

``` ruby
Ironfan.cluster 'broken' do
  cloud(:ec2) do
    permanent           false
    availability_zones  ['us-east-1d']
    flavor              'c1.medium'
    backing             'ebs'
    image_name          'ironfan-natty'
    bootstrap_distro    'ubuntu10.04-ironfan'
    chef_client_script  'client.rb'
    mount_ephemerals
  end
  facet :worker do
    instances           1
  end
end
```

**Comment by mrflip** [comment]
I think that's cause there's no ironfan-natty 32-bit AMI, and c1.mediums default to 32-bit in ironfan.  But I thought I made it complain early if that happens.  
1. Does the error persist if you `image_name 'natty'`
2. Does the error persist if you add `bits 64`

If so, then the problem is that it didn't complain about a missing AMI.

**Comment by fractaloop** [comment]
Solution 1 seems to have solved the issue. Do we not have an ironfan
specific image?

**Comment by temujin9** [comment]
We do, but something about that matching is not picking it up for the c1.medium. Your first place to look should be your knife-org.rb, which has (in our environment) a small bit in it poking the correct image into the right place.

**Comment by fractaloop** [comment]
Solution 2 seems to be the right one. The natty image was of course not configured to use with our standard practices.
