### ISSUE TITLE
ironfan vagrant usage documentation

### ISSUE THREAD

**Issue by dougnukem** [infochimps-labs/ironfan#231]
I'm trying to use ironfan and homebase and testing my cluster locally.

I noticed there was an ironfan-ci project that listed instructions on using the 'knife cluster vm' command, but that doesn't seem to be a valid cluster command.

Does ironfan support using vagrant to launch and test a cluster locally?

**Comment by temujin9** [comment]
Unfortunately, the current edition does not: it was an experimental feature, which got pulled for lack of available support bandwidth internally. We're closer to a situation where a VirtualBox provider could be written, but it's not yet implemented.

**Comment by dougnukem** [comment]
I think I'm going to research getting vagrant to work with Ironfan, it'd be really nice if I could test cluster definitions locally and be able to deploy that same definition in dev, staging and production environments.

Has there been any integration or research into  [knife-solo](https://github.com/matschaffer/knife-solo), that might integrate well as an alternative to requiring a chef server for cluster testing and deployment, and might be a decent bridge between vagrant and ironfan (e.g. knife-solo could deploy to vanilla vagrant instances).

**Comment by dezmodue** [comment]
Perhaps the vagrant plugin for knife might be a good starting point
https://github.com/garrettux/knife-vagrant?

S

**Comment by temujin9** [comment]
It feels like Vagrant may be the wrong choice of target; it's largely a shim over VirtualBox, and one largely intended for end-users (rather than being a programmable interface itself). That makes the work of getting it running extra difficult.

knife-solo is certainly an interesting possibility. Our last iteration relied on a local Chef server, which was a bit clunky.

See https://github.com/infochimps-labs/ironfan/issues/205 for further discussion. Closing this ticket as duplicate.
