### ISSUE TITLE
Can a cluster be a dependency for another cluster

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#49]
We are looking for a solution that would help us in a continuous deployment scenario. From what I can see, cluster_chef can do a lot of the heavy lifting.  I'm curious about this, though.  The infrastructure is defined as a number of components that work together.  A database, a web server, a few app servers, a proxy, etc. Once in a while, an entire class of application servers will be replaced to effect a clean software build. So if I have software foo-1.0.1 and foo-1.0.2, and I run foo on 5 servers, I would like to bring up the new version by deploying 1.0.2 onto 5 new servers, and then when they're up I can phase out the 5 old servers gradually to make sure I haven't introduced a regression.

Can cluster_chef give me a way to describe that two (or more?) instances of the same service at two (or more?) revisions should both be running?  My current thinking is that I can see this taking the form of defining each deployment as a set of dependencies on specific clusters.  E.g. app-cluster-release-20110926-0001 and app-cluster-release-20110926-0002 are the same app at different release levels.  Each one is a "deployment" of the app.  If I have a dependent app, the deployment processes would seem to need a way to refer to "the clusters of applications running production code" (where there can be >1 revisions of production code at any time) and these references would be replaced over time by something (probably a continuous integration hook) so that when a deployment is triggered, a new app-cluster-release is triggered, everything that depends on the app-cluster will, at their next cluster_chef client invocation, note that the revision has been updated, and re-configure themselves appropriately (according to logic in our cookbooks).

There are probably some gaps in the explanation I'm providing here, but I'd love to talk about this some more.  It'd be nice to have this functionality, especially if there's a way to do this already (e.g. perhaps I should be treating the entire environment as one very large cluster, and add and remove facets to make this work?)

Thanks!

-Peter

**Comment by mrflip** [comment]
We currently do this at the role and cluster level -- we have staging and production versions of most clusters; these typically differ only in the minor attribute overrides that are applied in role files. (We expressly specify the SHA of the git commit for each deployed component).

This is done by the clunky means of making production and deploy be distinct clusters -- effective when there are two, not so much otherwise.

I do think a lot of what you want though can be done using cluster_service_discovery.

If you spin up a new database facet, and it announces that it provides the service foocluster-jobqueue-20110926, then you can just tell all newer machines to connect, not to any old job queue, but to the foocluster-jobqueue-20110926. You can switch towards or away from a new rev of the job queue by updating the chef attribute that tells the clients of that machine what service to discover.

Does that make sense?  You'll have to do some stuff in cluster_service_discovery (to accept a version value) and in the connecting recipes (to supply it and to use it) but it should be quite feasible

**Comment by mrflip** [comment]
Closing the issue, but if using cluster_service_discovery as I described doesn't do the trick please re-open.

**Comment by pcn** [comment]
I'm using it now and cluster_service_discovery makes some sense to me know and I agree that it should be able to do what I'm interested in.  I think that since bringing up a database instance is expensive in terms of loading a data dump I will end up trying to use databags to store database configs, but I'll be using this to try to allow for redundant clusters.
