### ISSUE TITLE
knife cluster doesn't respect -i 

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#53]
It seems that when launching a cluster the -i flag doesn't get used, so an alternate ssh key can't be provided:

``` bash
$ knife cluster -c /Users/pn/.chef/knife-utility.rb -i ~/.ssh/id_1XXXXXX2 launch demosimple homebase --bootstrap
  +------------+-----------------------+----+------------+---------+------------+------------+-------+-------------+-------------+--------+-----------+
  | Elastic IP | Name                  | AZ | Created At | Volumes | Private IP | InstanceID | Image | State       | launchable? | Flavor | Public IP |
  +------------+-----------------------+----+------------+---------+------------+------------+-------+-------------+-------------+--------+-----------+
  |            | demosimple-homebase-0 |    |            |         |            |            |       | not running | true        |        |           |
  +------------+-----------------------+----+------------+---------+------------+------------+-------+-------------+-------------+--------+-----------+

Making security groups:
["authorizing group for", "demosimple", "demosimple", nil]
["authorizing group for", "nfs_server", "nfs_client", nil]

Launching machines:
ERROR: Fog::Service::NotFound: The key pair 'demosimple' does not exist
```

I think it'd make sense to allow an alternate id to be provided for the cluster so multiple clusters can be managed.

**Comment by mrflip** [comment]
Problem is in https://github.com/infochimps/cluster_chef/blob/master/lib/cluster_chef/knife/cluster_ssh.rb#L53 -- the target identity file is clobbering the one from the commandline (If I recall, this isn't the only config option with this issue). 

Config can come from several places in chef, but if not given we want to use  "#{keypair_dir}/{cluster_name}.pem" as the identity file. By the time we get to that spot in the cluster_ssh script, chef's opinion on the matter is formed, and we don't know whether that came from the commandline or a default or what. 

It's possible this is just as easy as making it not do a default, then letting chef win by if set (and using the cluster name otherwise).

If not, you'll have to either
- dive deeper into the chef config, 
- kludge: figure out whether the value was set on the commandline or something.

**Comment by pcn** [comment]
OK, I'll close this for future reference.  I'm not sure where this is on my list of priorities.

Thanks!

**Comment by pcn** [comment]
It seems like I need to do a run-around again:

<pre>
698 pn@PN-mac 23:06 ~/new-gems/gems $ diff -u ~/dvcs/chef/chef/lib/chef/knife/bootstrap.rb ./chef-0.10.4/lib/chef/knife/bootstrap.rb
--- /Users/pn/dvcs/chef/chef/lib/chef/knife/bootstrap.rb        2011-11-08 00:11:43.000000000 -0500
+++ ./chef-0.10.4/lib/chef/knife/bootstrap.rb   2011-12-08 23:01:29.000000000 -0500
@@ -178,10 +177,9 @@
         ssh.config[:ssh_user] = config[:ssh_user]
         ssh.config[:ssh_password] = config[:ssh_password]
         ssh.config[:ssh_port] = Chef::Config[:knife][:ssh_port] || config[:ssh_port]
-        ssh.config[:identity_file] = config[:identity_file]
+        ssh.config[:identity_file] = Chef::Config[:knife][:aws_ssh_key_id] || config[:identity_file]
         ssh.config[:manual] = true
         ssh.config[:no_host_key_verify] = config[:no_host_key_verify]
-        ssh.config[:on_error] = :raise
         ssh
</pre>


Only the :identity_file option is needed, the :on_error symbol seems to be a difference in the chef repo itself.

Anyway, storing this here for future reference.  Creating the option in .knife.rb:

<pre>
knife[:aws_ssh_key_id]             = "#{ENV['CLUSTER']}"
</pre>


allows me to set the environment variable $CLUSTER to point to the id file that I want, and the config is found.  I don't really like this hack, but I'm memorializing it because otherwise I'll lose this again once 0.10.6 comes out and I upgrade the gem.

**Comment by pcn** [comment]
Footnote: the better fix in version_3 is at https://github.com/infochimps/cluster_chef/pull/93
