### ISSUE TITLE
Relocate cookbooks, roles and clusters into separate repo(s)

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#61]
Cluster chef currently consists of the following separate(able) concerns:
- **cluster_chef tools**
  - the DSL that lets you define clusters
  - the knife commands which use that DSL
  - optional bootstrap scripts for a machine image that can then launch bootstrap-less
- **cluster-oriented cookbooks**
  - `cluster_service_discovery` (recipes to let clusters discover services using chef-server's search)
  - ?others?
- **cloud utility cookbooks**
  - motd, system_internals (swappiness, ulimit, etc)
- **big data cookbooks** (hadoop, cassandra, redis, etc):
  - cookbooks
  - roles
  - clusters

I think it's time to separate those into at least two repos.

REQUEST FOR COMMENTS: 
#### Division of concerns

It's clear that the cluster_chef tools and the big data cookbooks should be divorced, but I don't know whether there should be further subdivision.

Proposed:
- `cluster_chef` holds only the DSL, knife commands, and bootstrap scripts -- basically the stuff in `lib/`, along with the gemspec etc.
- `cluster_chef-systems` -- holds cookbooks, roles and example clusters that use them. 
  - Utility cookbooks (`cluster_service_discovery`, motd, etc) and system cookbooks(hadoop, cassandra, etc) are housed in two separate folders. 
  - The standard layout would just include the cookbooks, but a cluster-oriented approach demands that the roles travel along too
- (possibly) `cluster_chef-chef-repo` (??better name, anyone??) -- a fork of https://github.com/opscode/chef-repo that integrates the above
#### Handling of cookbooks that originate from opscode-cookbooks

Right now we _copy_ standard cookbooks from opscode's repo into the `cookbooks` directory. This lets us version them separately, but means we have to track them, and could cause conflicts with the majority of people who will be pulling from opscode-cookbooks already.
1. omit entirely, but list as dependencies (my vote)
2. `git subtree` pull them into the cluster_chef-cookbooks repo
3. copy them in as we've been doing
4. `git submodule` opscode-cookbooks and symlink
#### Organization of new repo(s)

Opscode recommends a [standard layout for your chef repo](https://github.com/opscode/chef-repo). We should make the new arrangement work seamlessly within that structure.

The new layout should 
- easy to integrate if you have your own existing chef-repo
- straightforward for a new chef user to adopt
- either mirror or be what we actually use

Proposed, but this doesn't feel solid to me yet:

```
  clusters/                 # internal clusters
  roles/                    # internal roles
  site-cookbooks/           # internal cookbooks

  systems-cookbooks@        # symlink to cluster_chef-systems/systems-cookbooks
  cloud-cookbooks@          # symlink to cluster_chef-systems/cloud-cookbooks
  opscode-cookbooks/        # git submodule of https://github.com/opscode/cookbooks

  cluster_chef-systems      # git submodule of https://github.com/infochimps/cluster_chef-systems
    clusters/               
    roles/                  
    systems-cookbooks/      # hadoop, cassandra, etc
    cloud-cookbooks/        # cluster_service_discovery, motd, etc

  .chef/                    # knife config, keypairs, etc
  certificates/
  config/
  data_bags/
  environments/    
```

The idea is that you can either just include the cookbooks or clusters directories in your config file, or symlink selectively.

**Comment by arp** [comment]
#### Division of concerns

`cluster_chef` and `cluster_chef-systems` could both be gems IMO. As for `chef-repo` question, I think it makes sense to provide a path to easy integration of already some existing company's `chef-repo` with the functionality provided by `cluster_chef`.

For example, I may need to run some common roles/recipes on every machine in the company. Some machines may be controlled by `cluster_chef`, and others could be managed separately. Thus, I'd like to have a single `chef-repo` and `knife.rb` for all of them and have no symlinks there.

Actually, that's the way it already works in my case:

`cluster_chef` is installed as a gem by Bundler (we have `Gemfile` in our `chef-repo`), and all `cluster` knife plugins are visible to knife when it is executed as `bundle exec knife` (I'm going to eliminate that requirement to prepend `bundle exec`).

`cookbooks` and `site-cookbooks` are included through calling `bundle show cluster_chef` inside of `knife.rb`.

Maybe it could be worth organizing all the dependencies in some single file and allow to include them all at once by adding smth akin to `require "cluster_chef/knife"` in company's `knife.rb`? Generally, I vote for one-step integration.

#### Handling of cookbooks that originate from opscode-cookbooks

I agree that opscode cookbooks shouldn't be a part of the `cluster_chef` gem at all. Especially given that Chef obsoletes merging of duplicate cookbooks pretty soon. Listing them as deps is great, probably they should be provided as a single list as well (I'm not sure it's easy to list them all once they are dissolved in metadata of several different cookbooks). As a separate idea, some kind of `Cookfile` that resembles Bundler's `Gemfile` could solve that.

#### Organization of new repo(s)

Overall, looks like a good direction, but there are two things that seem somewhat sloppy to me:
- symlinks, just because they may easily become messy and unmaintainable (and require some manual work)
- creating too many directories at the top level of `chef-repo`. Does it sound reasonable to hide all of different cookbook types under single directory?

**Comment by aseever** [comment]
+1 for cluster_chef & cluster_chef-systems decoupled.

**Comment by mrflip** [comment]
Revised proposal:

```
  clusters/                 
    { actual clusters }
  roles/               
    { roles }
    { symlinks to things in vendor/cluster_chef/roles }

  site-cookbooks/
    { directories holding internal cookbooks }

  cookbooks/ 
    { symlinks into vendor/opscode-cookbooks }
    { symlinks into vendor/cluster_chef-systems/site-cookbooks }

  vendor/
    opscode/cookbooks/      # git submodule of https://github.com/opscode/cookbooks
    cluster_chef-systems/   # git submodule of https://github.com/infochimps/cluster_chef-systems
      site-cookbooks/         # hadoop, cassandra, cluster_service_discovery, etc.
      roles/
      examples/
        clusters/           # example clusters
        roles/              # roles (if any) needed for just the example clusters

  .chef/                    # knife config, keypairs, etc
  certificates/
  config/
  data_bags/
  environments/    
```

**Comment by arp** [comment]
Revised proposal definitely looks good to me

**Comment by pcn** [comment]
Based on today's summit, it looks like opscode cookbooks are going to be broken out into individual repos.  Would hat influence any of the structure in the proposal?

**Comment by mrflip** [comment]
Yes, good call @pcn. Proposed:
- cookbooks as individual repos, under either http://github.com/infochimps-labs or http://github.com/infochimps-cookbooks. (@temujin9 or @aseever any preference?) We can fork the official cookbooks into that repo to inject cluster_chef friendly changes where strictly necessary.
- repo `cluster_chef-homebase` that holds clusters, roles and submodules those cookbooks
- cluster_chef repo becomes just the knife tools and supporting code
- cluster_chef-munger to hold the cookbook munger which has secretly sprouted up inside lib/cluster_chef and grown to needs-its-own-project size.

**Comment by temujin9** [comment]
+1 for following Opscode's cookbook == repo plan.

My preference would be infochimps-cookbooks: there are going to be many of them, and we don't want to lose everything else in the infochimps-labs in the morass. The homebase and munger should still go into the labs themselves.

**Comment by mrflip** [comment]
to check: homebase, munger and tools go in infochimps-labs -- and only
cookbooks go in infochimps-cookbooks <-- is this your recommendation

flip

On Thu, Dec 1, 2011 at 12:26 PM, Nathaniel Eliot <
reply@reply.github.com

> wrote:
> 
> +1 for following Opscode's cookbook == repo plan.
> 
> My preference would be infochimps-cookbooks: there are going to be many of
> them, and we don't want to lose everything else in the infochimps-labs in
> the morass. The homebase and munger should still go into the labs
> themselves.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/61#issuecomment-2978429

## 

infochimps.com - discover data

**Comment by temujin9** [comment]
That is it exactly.
On Dec 1, 2011 8:33 PM, "Philip (flip) Kromer" <
reply@reply.github.com>
wrote:

**Comment by mrflip** [comment]
Here's where we've landed:
- every cookbook is now present on [infochimps-cookbooks' github](http://github.com/infochimps-cookbooks) in its own repo. 
  - infochimps-maintained ones are their own root repos
  - forks of other people's ones are forked
  - ones from the opscode/cookbooks repo are git-subtree extracts, so they don't look like github forks
- Each cookbook's history is present in that repo, at least as far back as the may 2011 re-org.
- They are all git-subtree'd into [infochimps-labs/cluster_chef-homebase](http://github.com/infochimps-labs/cluster_chef-homebase): 
  - infochimps-maintained cookbooks: git-subtree from the infochimps-cookbooks home, placed in vendor/infochimps
  - Other cookbooks: git-subtree from the infochimps-cookbooks fork, placed in `vendor/{original_author}`
  - Opscode community cookboks: _git submodule_ of the [infochimps-labs](http://github.com/infochimps-labs/opscode_cookbooks) fork of opscode/cookbooks is into vendor/opscode. This is _all_ their cookbooks.
- The actual collection we use is defined by symlinks in `cookbooks/foo` to `../vendor/whatever/foo`. This is everything in vendor/infochimps, vendor/{other}, and the curated subset of things in vendor/opscode.

**Comment by temujin9** [comment]
+1. This is something we'll want to post to http://wiki.opscode.com/pages/viewpage.action?pageId=21398075 fairly soon: we can offer them guidance on how to do their split, having already done one ourselves.

**Comment by pcn** [comment]
I'm glad this has been done.  It was a bit of a bomb when it dropped - that is having to run around and find the cookbooks that I used, but it made it a million times easier to submit patches in the form of pull requests.

**Comment by mrflip** [comment]
yeah sorry about the poor communication there -- I had to go deep into the catacombs and wrestle many a balrog to get git gotten where we wanted git to get. Hopefully you didn't pull during the period where we had everything submoduled, realized how terrible that was and had to rewrite history to back out the change. I have grey hairs and a third eye I didn't have before.

**Comment by lastobelus** [comment]
This no longer seems to reflect the current state of affairs. https://github.com/infochimps-cookbooks doesn't exist anymore, and ironfan-homebase seems to represent the opscode cookbooks before split.

Any advice on the best way to manage updating opscode cookbooks in a forked ironfan-homebase? My initial idea is to just start taking advantage of the merging that knife install now does, and do knife cookbook install site XXXX for the cookbooks I want to update. Any tips for finding necessary ironfan customizations in the cookbooks that are not part of pantry?

**Comment by temujin9** [comment]
We reversed direction, after finding the practical time costs and implications for maintaining the per-cookbook split. It's a great idea for Opscode, because of their central position in the community, but we're not in the same business.

The customization is of two major varieties: standardization of attributes structure, and abstraction of common tasks (service discovery, setting up standard daemon directories, etc.). The first is spread all over; the second is going to be in resource provider calls to the silverware cookbook. They are somewhat interdependent, in that silverware abstractions depend on the standardized structure of attributes to do their thing.

The `knife cookbook install site` route sounds about right for first stab at merging upstream changes. If you fork the cookbooks repos we submodule ([ironfan-pantry](https://github.com/infochimps-labs/ironfan-pantry) and [opscode_cookbooks](https://github.com/infochimps-labs/opscode_cookbooks)), we'd be glad to get pull requests for upstream merges you've gotten to work.

**Comment by lastobelus** [comment]
I agree that per cookbook repos would be time consuming, and maybe even detrimental to the continuity of the project. 

Thanks for the advice. Is there a cookbook(s) in particular that comes to mind that would be helpful for me to look at to see "canonical" examples of attribute standardization and using silverware -- particularly the discovery mechanism?

What I have done so far is to build a simple lamp cluster. I was trying to use the opscode application & application_php & database cookbooks (but I used ironfan to handle the ebs volume); however I think it would be better to use the ironfan discovery mechanism to connect appservers with the db instead of opscode's database_master_role.

I'm going to look next at how haproxy is managed in the example clusters and try to add load balancing to my cluster in the ironfan Way.

**Comment by temujin9** [comment]
hadoop_cluster is probably the fullest example, though it's also a very complex one. elasticsearch is a much simpler example, and nodejs apparently just got a makeover recently.

LAMP would be an excellent set of cookbooks to bring into the Ironfan/Silverware world. We're a Ruby heavy shop, so we don't use it internally, but it's something nearly anyone with web background understands, and will make a great "getting started" example.

**Comment by temujin9** [comment]
I just found an old link to [knife-github-cookbooks](https://github.com/websterclay/knife-github-cookbooks), which might help in merging changes from disparate upstreams (ours and Opscode). Good luck!

**Comment by lastobelus** [comment]
Thanks temujin9!

**Comment by lastobelus** [comment]
Have you guys looked at https://github.com/RiotGames/berkshelf?

It seems like it would be a pretty good fit, and re-working the current ironfan-homebase to use it would be fairly straightforward. It would reduce the number of git submodules, and make it easier to do things like (temporarily) use a fork of an opscode cookbook. It would also encourage the habit of working on cookbooks independently, rather than in a particular homebase/chef-repo.

It could work quite well together with the pantry idea, by using a :path source for cookbooks that come from a pantry. But at the same time it would make working with forks of individually source-controlled cookbooks much easier.

**Comment by mrflip** [comment]
The best "canonical" cookbook is ganglia -- it's has all the common complex
things without any of the hairy uncommon complex things.

flip

On Mon, Jul 16, 2012 at 11:01 PM, Michael Johnston <
reply@reply.github.com

> wrote:
> 
> Have you guys looked at https://github.com/RiotGames/berkshelf?
> 
> It seems like it would be a pretty good fit, and re-working the current
> ironfan-homebase to use it would be fairly straightforward. It would reduce
> the number of git submodules, and make it easier to do things like
> (temporarily) use a fork of an opscode cookbook. It would also encourage
> the habit of working on cookbooks independently, rather than in a
> particular homebase/chef-repo.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps-labs/ironfan/issues/61#issuecomment-7026187

## 

infochimps.com - discover data

**Comment by temujin9** [comment]
@mrflip Thank you: this isn't the only time I've been asked for a good silverware example.

@lastobelus Berkshelf looks good, but I'm pretty sure I don't want to tackle it immediately. If you wanted to build a setup that used it, I would certainly be game for testing and including it. Otherwise, it's only likely if and when our CI development or other architectural concerns warrant it.

**Comment by lastobelus** [comment]
Thanks, I will have a look at the ganglia cookbook. 

I have switched this [homebase fork](https://github.com/lastobelus/kiwi-ironfan-homebase) to Berkshelf; after I've developed it in a while I'll give some feedback on how it worked out for me.

[edit] I had to make that homebase private, but I will try to make a public fork that uses berkshelf when I have a chance.
