### ISSUE TITLE
"knife cluster launch <clustername> --bootstrap" failing because clients already created before bootstrap registration; Using version_3

### ISSUE THREAD

**Issue by redbeard** [infochimps-labs/ironfan#88]
Results in 409 error when the bootstrap script tries to register the client.

```
[Wed, 21 Dec 2011 05:13:45 +0000] INFO: *** Chef 0.10.8 ***
DEBUG: received packet nr 410 type 94 len 124
INFO: channel_data: 0 102b
[Wed, 21 Dec 2011 05:13:45 +0000] INFO: Client key /etc/chef/client.pem is not present - registering
DEBUG: read 148 bytes
DEBUG: received packet nr 411 type 94 len 124
INFO: channel_data: 0 100b
[Wed, 21 Dec 2011 05:13:46 +0000] INFO: HTTP Request Returned 409 Conflict: Client already exists.
DEBUG: read 340 bytes
DEBUG: received packet nr 412 type 94 len 316
INFO: channel_data: 0 299b
[Wed, 21 Dec 2011 05:13:46 +0000] INFO: HTTP Request Returned 403 Forbidden: Merb::ControllerExceptions::Forbidden
[Wed, 21 Dec 2011 05:13:46 +0000] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[Wed, 21 Dec 2011 05:13:46 +0000] FATAL: Net::HTTPServerException: 403 "Forbidden"
```

Unless I'm missing some custom bootstrap that needs to be somewhere (my homebase is based on infochimps-labs/cluster_chef-homebase )

**Comment by redbeard** [comment]
May have to do with the fact that knife is not looking in the right place for the bootstraps it is using the default chef ones instead of using the bootstraps from cluster_chef-knife. 

Am I missing some configuration option perhaps?

From the log:

```
Looking for bootstrap template in /Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/chef-0.10.8/lib/chef/knife/bootstrap
DEBUG: Found bootstrap template in /Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/chef-0.10.8/lib/chef/knife/bootstrap
```

**Comment by mrflip** [comment]
oh phooey. hrm.

So: 
- due to a limitation in the opscode API cluster chef right now manufactures the client key on its end.
- This works fine when you use our patched bootstrap script --- `bootstrap_distro    'ubuntu10.04-cluster_chef'` (or the 11.xx version). 
- the default bootstrap scripts do not pay any attention to the client key, and don't make it easy to patch in arbitrary code without running a custom bootstrap script

Without thinking very hard, I assumed 'gee, making people use our custom bootstrap scripts is kinda intrusive' and set the example clusters to by default not specify `ubuntu10.04-cluster_chef`
- Are you able to use that bootstrap script -- as in a) does it work, and b) does it offend you? Adopting it (or the parts of it that inject the client key) is the most straightforward thing to do right now.
- Awaiting a better fix, I'll edit the cluster definitions to refer to the custom bootstrap script

The client vs node generation problem is just a big angry goatrope. Hopefully we can get something better in place before v3 launch.  I'm going to open that as a separate bug; close this if `bootstrap_distro 'ubuntu10.04-cluster_chef'` gets you happily bootstrapping.

**Comment by redbeard** [comment]
Aha, that's how you set the default distro flag for the cluster!

I just modified --bootstrap to accept --distro and did it that way (the pull req. that was submitted).

Using the patched bootstrap got it all going. Happy to close this.

**Comment by redbeard** [comment]
Just one additional comment/suggestion.

Once you register the client, instead of patching the bootstrap, is it possible to upload the client key to [:host]/etc/chef/client.pem? 

If so the default bootstrap template will skip the registration part.

**Comment by mrflip** [comment]
oh, so I run two knife ssh stages -- one that teleports in the key, and one that does the bootstrap?

Yes, that would work

**Comment by mrflip** [comment]
(further discussion at #90, "Creating chef client at launch causes chaos. Not creating chef client at launch causes chaos." )
